# Generated by Django 3.0.5 on 2020-08-30 12:54

from django.db import migrations, models
import element.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.TextField(unique=True)),
                ('fg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('bg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('fg_pattern', models.CharField(choices=[('NONE', 'NONE'), ('STAR', 'STAR'), ('SQUARE', 'SQUARE'), ('CIRCLE', 'CIRCLE'), ('CROSS', 'CROSS'), ('PLUS', 'PLUS')], default='NONE', max_length=32)),
                ('bg_pattern', models.CharField(choices=[('FLAT', 'FLAT'), ('LEFT-RIGHT', 'LEFT-RIGHT'), ('TOP-BOTTOM', 'TOP-BOTTOM'), ('TOPLEFT-BOTTOMRIGHT', 'TOPLEFT-BOTTOMRIGHT'), ('TOPRIGHT-BOTTOMLEFT', 'TOPRIGHT-BOTTOMLEFT')], default='FLAT', max_length=32)),
                ('default', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=16)),
                ('sequential_number', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('ingredients', models.ManyToManyField(to='element.Element')),
            ],
        ),
    ]
