# Generated by Django 3.0.5 on 2020-09-01 14:11

from django.db import migrations, models
import element.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.TextField(unique=True)),
                ('fg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('bg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('fg_pattern', models.CharField(choices=[('NONE', 'NONE'), ('STAR', 'STAR'), ('SQUARE', 'SQUARE'), ('CIRCLE', 'CIRCLE'), ('CROSS', 'CROSS'), ('PLUS', 'PLUS')], default='NONE', max_length=32)),
                ('bg_pattern', models.CharField(choices=[('FLAT', 'FLAT'), ('LEFT-RIGHT', 'LEFT-RIGHT'), ('TOP-BOTTOM', 'TOP-BOTTOM'), ('TOPLEFT-BOTTOMRIGHT', 'TOPLEFT-BOTTOMRIGHT'), ('TOPRIGHT-BOTTOMLEFT', 'TOPRIGHT-BOTTOMLEFT')], default='FLAT', max_length=32)),
                ('default', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=32)),
                ('sequential_number', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('ingredients', models.ManyToManyField(related_name='possible_recipes', to='element.Element')),
            ],
        ),
        migrations.CreateModel(
            name='NewElementSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('fg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('bg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('fg_pattern', models.CharField(choices=[('NONE', 'NONE'), ('STAR', 'STAR'), ('SQUARE', 'SQUARE'), ('CIRCLE', 'CIRCLE'), ('CROSS', 'CROSS'), ('PLUS', 'PLUS')], default='NONE', max_length=32)),
                ('bg_pattern', models.CharField(choices=[('FLAT', 'FLAT'), ('LEFT-RIGHT', 'LEFT-RIGHT'), ('TOP-BOTTOM', 'TOP-BOTTOM'), ('TOPLEFT-BOTTOMRIGHT', 'TOPLEFT-BOTTOMRIGHT'), ('TOPRIGHT-BOTTOMLEFT', 'TOPRIGHT-BOTTOMLEFT')], default='FLAT', max_length=32)),
                ('current', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=10)),
                ('create_date', models.DateTimeField()),
                ('voted_ips', models.TextField(default='')),
                ('ingredients', models.ManyToManyField(related_name='suggested_recipes', to='element.Element')),
            ],
        ),
    ]
