# Generated by Django 3.0.5 on 2020-08-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='ingredients',
            field=models.ManyToManyField(related_name='possible_recipes', to='element.Element'),
        ),
    ]
