# Generated by Django 3.0.5 on 2020-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newelementsuggestion',
            name='verge',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newelementsuggestion',
            name='current',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newelementsuggestion',
            name='target',
            field=models.IntegerField(default=1),
        ),
    ]
