# Generated by Django 3.0.5 on 2020-09-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0002_auto_20200907_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='newelementsuggestion',
            name='voters',
            field=models.TextField(default='{"up":[],"down":[]}'),
        ),
    ]
