# Generated by Django 3.0.5 on 2020-09-08 22:42

from django.db import migrations, models
import django.db.models.deletion
import element.models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0003_newelementsuggestion_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('fg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('bg_colors', models.TextField(null=True, validators=[element.models.color_list_validator])),
                ('fg_pattern', models.CharField(choices=[('NONE', 'NONE'), ('STAR', 'STAR'), ('SQUARE', 'SQUARE'), ('CIRCLE', 'CIRCLE'), ('CROSS', 'CROSS'), ('PLUS', 'PLUS')], default='NONE', max_length=32, null=True)),
                ('bg_pattern', models.CharField(choices=[('FLAT', 'FLAT'), ('LEFT-RIGHT', 'LEFT-RIGHT'), ('TOP-BOTTOM', 'TOP-BOTTOM'), ('TOPLEFT-BOTTOMRIGHT', 'TOPLEFT-BOTTOMRIGHT'), ('TOPRIGHT-BOTTOMLEFT', 'TOPRIGHT-BOTTOMLEFT')], default='FLAT', max_length=32, null=True)),
                ('current', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=1)),
                ('verge', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField()),
                ('voters', models.TextField(default='{"up":[],"down":[]}')),
                ('voted_ips', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='NewElementSuggestion',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='ingredients',
            field=models.ManyToManyField(related_name='suggested_recipes', to='element.Element'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='possible_recipes', to='element.Element'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producing_recipes', to='element.Element'),
        ),
    ]
