# Generated by Django 3.0.5 on 2020-09-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0007_auto_20200922_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_type',
            field=models.CharField(default='new', max_length=10),
            preserve_default=False,
        ),
    ]
