# Generated by Django 3.1.1 on 2020-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0008_suggestion_suggestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='edit_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='target',
            field=models.IntegerField(default=2),
        ),
    ]
