# Generated by Django 3.1.1 on 2020-10-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0009_auto_20201021_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion_type',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='target',
            field=models.IntegerField(default=1),
        ),
    ]
