# Generated by Django 3.1.1 on 2020-12-02 21:43

from django.db import migrations, models
import element.models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0011_suggestion_suggestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.TextField(unique=True, validators=[element.models.name_validator]),
        ),
    ]
