# Generated by Django 3.1.1 on 2020-12-02 22:07

from django.db import migrations, models
import element.models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0012_auto_20201202_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='bg_colors',
            field=models.TextField(default='#FFFFFF,#FFFFFF', validators=[element.models.color_list_validator]),
        ),
        migrations.AlterField(
            model_name='element',
            name='fg_colors',
            field=models.TextField(default='#FFFFFF,#FFFFFF', validators=[element.models.color_list_validator]),
        ),
    ]
