# Generated by Django 3.1.1 on 2020-12-02 22:26

from django.db import migrations, models
import element.models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0013_auto_20201202_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='bg_colors',
            field=models.TextField(default='#FFFFFF,#FFFFFF', validators=[element.models.color_list_validator]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='bg_pattern',
            field=models.CharField(choices=[('FLAT', 'FLAT'), ('LEFT-RIGHT', 'LEFT-RIGHT'), ('TOP-BOTTOM', 'TOP-BOTTOM'), ('TOPLEFT-BOTTOMRIGHT', 'TOPLEFT-BOTTOMRIGHT'), ('TOPRIGHT-BOTTOMLEFT', 'TOPRIGHT-BOTTOMLEFT')], default='FLAT', max_length=32),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='fg_colors',
            field=models.TextField(default='#FFFFFF,#FFFFFF', validators=[element.models.color_list_validator]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='fg_pattern',
            field=models.CharField(choices=[('NONE', 'NONE'), ('STAR', 'STAR'), ('SQUARE', 'SQUARE'), ('CIRCLE', 'CIRCLE'), ('CROSS', 'CROSS'), ('PLUS', 'PLUS')], default='NONE', max_length=32),
        ),
    ]
