# Generated by Django 3.1.1 on 2020-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('play_channel', models.BooleanField(default=False)),
                ('vote_channel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
