# Generated by Django 3.1.1 on 2020-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0011_suggestion_suggestion_type'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='has_elements',
            field=models.ManyToManyField(to='element.Element'),
        ),
    ]
