# Generated by Django 3.1.1 on 2020-12-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0012_auto_20201202_2143'),
        ('bot', '0002_discorduser_has_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='last_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='element.recipe'),
        ),
    ]
