# Generated by Django 3.1.1 on 2020-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_discorduser_last_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='last_recipe',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='last_ingredients',
            field=models.TextField(null=True),
        ),
    ]
